version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore all major updates for all dependencies
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

      # Ignore both major and minor updates for Apache Camel
      - dependency-name: "org.apache.camel:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

      # If using Camel Spring Boot dependencies, ignore those too
      - dependency-name: "org.apache.camel.springboot:*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      -
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eclipse-temurin"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"