common:
  env: prd
  ingress:
    enabled: false
  service:
    enabled: false
    internalPort: 9001
  container:
    forceReplicas: 2

configMap:
  gcpProjectId: ent-kingu-prd
  pubSubProjectId: ent-kingu-prd
  blobstoreProjectId: ent-kingu-prd
  gcsBucketName: ror-kingu-production

sql:
  instance: ent-tiamat-prd:europe-west1:tiamat-db-1-replica=tcp:5432
