common:
  env: dev
  ingress:
    enabled: false
  service:
    enabled: false
    internalPort: 9001
  deployment:
    replicas: 2

configMap:
  gcpProjectId: ent-kingu-dev
  pubSubProjectId: ent-kingu-dev
  blobstoreProjectId: ent-kingu-dev
  gcsBucketName: ror-kingu-dev

sql:
  instance: ent-tiamat-dev:europe-west1:tiamat-db-1-replica=tcp:5432
