common:
  env: tst
  ingress:
    enabled: false
  service:
    enabled: false
    internalPort: 9001
  replicas: 2

configMap:
  gcpProjectId: ent-kingu-tst
  pubSubProjectId: ent-kingu-tst
  blobstoreProjectId: ent-kingu-tst
  gcsBucketName: ror-kingu-test

sql:
  instance: ent-tiamat-tst:europe-west1:tiamat-db-1-replica=tcp:5432