apiVersion: v2
appVersion: "0.0.1"
description: Netex exporter
name: kingu
version: 0.1.0
keywords:
- kingu
sources:
- https://github.com/entur/kingu
maintainers:
- name: 'team-ror'
  email: team.rutedata@entur.org
engine: gotpl
dependencies:
  - name: common
    version: 1.17.5
    repository: "https://entur.github.io/helm-charts"
