apiVersion: v1
appVersion: "0.0.1"
description: Netex exporter
name: kingu
version: 0.1.0
keywords:
- kingu
sources:
- https://github.com/entur/kingu
maintainers:
- name: 'team-ror'
  email: team.rutedata@entur.org
engine: gotpl
