kingu:
  database: tiamat
common:
  app: kingu
  shortname: kingu
  team: ror
  container:
    image: <+artifacts.primary.image>
    memoryLimit: 10000
    memory: 7500
    cpu: 1.2
    uid: 2000
    probes:
      liveness:
        path: /actuator/health
        periodSeconds: 10
        failureThreshold: 3
      readiness:
        path: /actuator/health
        periodSeconds: 10
        failureThreshold: 3
    envFrom:
      - configMapRef:
          name: kingu-application
    prometheus:
      enabled: true
      path: /actuator/prometheus
    volumeMounts:
      - mountPath: /etc/application-config
        name: application-config
        readOnly: true
    volumes:
      - configMap:
          defaultMode: 420
          name: kingu-application
        name: application-config
  postgres:
    enabled: true
    cpu: 0.5
    cpuLimit: 0.5
  configmap:
    data:
      JDK_JAVA_OPTIONS: -server -Xss1024m -Xmx7g -Dspring.config.location=/etc/application-config/application.properties
        -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED
      TZ: Europe/Oslo
    enabled: true
    toEnv: true
  secrets:
    psql-credentials: [PGUSER, PGPASSWORD]
  env: "dev" # Set to your environment: dev, tst, or prd
  ingress:
    enabled: false
    host: "example.com" # Replace with your actual host
    trafficType: "internal" # or "external", as appropriate
sql:
  instance: "your-postgres-instance" # Replace with your actual Postgres instance name
configMap:
  pubSubProjectId: "your-gcp-project-id" # Replace with your actual GCP Pub/Sub project ID
