replicas: 2


deployment:
  name: kingu

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

resources:
  cpuLimit: 1200m
  memLimit: 10000Mi
  cpuRequest: 1200m
  memRequest: 7500Mi
  xss: 1024m
  xmx: 7g

secretMount:
   name: kingu-key
   mountPath: /etc/kingu/credentials.json
   subPath: credentials.json
   secretName: ror-kingu-sa-key
   readOnly: true


configMapMount:
   name: kingu-config

image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always



